services:
  - type: web
    name: techstore-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/cliente_web/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
